<?php
// This file will be automatically generated by setup.php
// If you are installing manually, rename this file to db.php and configure below:

$host = 'localhost';
$db   = 'cafe_pelotero';
$user = 'root';
$pass = '';
$charset = 'utf8mb4';

$dsn = "mysql:host=$host;dbname=$db;charset=$charset";
$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
];

try {
    $pdo = new PDO($dsn, $user, $pass, $options);
} catch (\PDOException $e) {
    // If this fails, it might be because the setup hasn't been run yet.
    // Redirect to setup if not an API request
    if (php_sapi_name() !== 'cli' && !strpos($_SERVER['REQUEST_URI'], 'setup.php')) {
        // Simple check to avoid infinite loops or breaking API calls
        // Ideally, the app should handle this check globally.
    }
    throw new \PDOException($e->getMessage(), (int)$e->getCode());
}
?>
